# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import structurer_pb2 as structurer__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in structurer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AddressStructurerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Structure = channel.unary_unary(
                '/com.jpmc.tfpm.address.proto.v1.AddressStructurerService/Structure',
                request_serializer=structurer__pb2.StructureRequest.SerializeToString,
                response_deserializer=structurer__pb2.StructureResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/com.jpmc.tfpm.address.proto.v1.AddressStructurerService/Health',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=structurer__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Capabilities = channel.unary_unary(
                '/com.jpmc.tfpm.address.proto.v1.AddressStructurerService/Capabilities',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=structurer__pb2.CapabilitiesResponse.FromString,
                _registered_method=True)


class AddressStructurerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Structure(self, request, context):
        """Structure a single raw address. Sidecars MUST be stateless and idempotent
        for a given (raw_address, country_hint, locale) tuple.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check for orchestration. MUST return within 100ms.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Capabilities(self, request, context):
        """Capability advertisement. Returned set of fields determines what the
        FieldMerger will accept from this structurer. Returning a field this
        structurer cannot populate is a contract violation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddressStructurerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Structure': grpc.unary_unary_rpc_method_handler(
                    servicer.Structure,
                    request_deserializer=structurer__pb2.StructureRequest.FromString,
                    response_serializer=structurer__pb2.StructureResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=structurer__pb2.HealthResponse.SerializeToString,
            ),
            'Capabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.Capabilities,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=structurer__pb2.CapabilitiesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.jpmc.tfpm.address.proto.v1.AddressStructurerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.jpmc.tfpm.address.proto.v1.AddressStructurerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AddressStructurerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Structure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.jpmc.tfpm.address.proto.v1.AddressStructurerService/Structure',
            structurer__pb2.StructureRequest.SerializeToString,
            structurer__pb2.StructureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.jpmc.tfpm.address.proto.v1.AddressStructurerService/Health',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            structurer__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Capabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.jpmc.tfpm.address.proto.v1.AddressStructurerService/Capabilities',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            structurer__pb2.CapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
