-- H2-compatible schema for local development (in-memory).
-- Mirrors the Oracle Liquibase schema without Oracle-specific features
-- (no partitioning, no INTERVAL, no IS JSON, no VARCHAR2).
-- Used when spring.profiles.active=local and liquibase.enabled=false.

-- 002: Idempotency keys
CREATE TABLE IF NOT EXISTS IDEMPOTENCY_KEYS (
    IDEM_KEY        VARCHAR(64)    NOT NULL,
    SOURCE_CHANNEL  VARCHAR(16)    NOT NULL,
    SOURCE_REF      VARCHAR(256),
    PROCESSED_AT    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    RESULT_REF      BIGINT,
    CONSTRAINT PK_IDEM PRIMARY KEY (IDEM_KEY)
);

-- 003: Structuring results
CREATE TABLE IF NOT EXISTS STRUCTURING_RESULTS (
    RESULT_ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CORRELATION_ID      VARCHAR(256)   NOT NULL,
    SOURCE_CHANNEL      VARCHAR(16)    NOT NULL,
    RAW_ADDRESS         VARCHAR(2000),
    COUNTRY_HINT        CHAR(2),
    FIELDS_JSON         CLOB,
    STRUCTURER_TRACE    CLOB,
    OVERALL_CONFIDENCE  DOUBLE,
    REQUIRES_REVIEW     CHAR(1) DEFAULT 'N',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 004: Exception queue
CREATE TABLE IF NOT EXISTS EXCEPTION_QUEUE (
    EXCEPTION_ID    BIGINT GENERATED ALWAYS AS IDENTITY,
    RESULT_ID       BIGINT         NOT NULL,
    REASON          VARCHAR(64)    NOT NULL,
    STATUS          VARCHAR(16) DEFAULT 'OPEN' NOT NULL,
    CLAIMED_BY      VARCHAR(64),
    CLAIMED_AT      TIMESTAMP,
    RESOLVED_BY     VARCHAR(64),
    RESOLVED_AT     TIMESTAMP,
    RESOLUTION_JSON CLOB,
    CREATED_AT      TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VERSION         INT DEFAULT 0 NOT NULL,
    CONSTRAINT PK_EXCEPTION PRIMARY KEY (EXCEPTION_ID)
);
CREATE INDEX IF NOT EXISTS IX_EXC_OPEN ON EXCEPTION_QUEUE (STATUS, CREATED_AT);
CREATE INDEX IF NOT EXISTS IX_EXC_RESULT ON EXCEPTION_QUEUE (RESULT_ID);

-- 005: Audit log
CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    AUDIT_ID     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    EVENT_TIME   TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EVENT_TYPE   VARCHAR(32)    NOT NULL,
    ACTOR        VARCHAR(64)    NOT NULL,
    ENTITY_TYPE  VARCHAR(32)    NOT NULL,
    ENTITY_ID    VARCHAR(64)    NOT NULL,
    DETAILS_JSON CLOB
);

-- 007: Field attributions
CREATE TABLE IF NOT EXISTS FIELD_ATTRIBUTIONS (
    ATTRIBUTION_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESULT_ID              BIGINT         NOT NULL,
    FIELD_NAME             VARCHAR(20)    NOT NULL,
    STRUCTURER_NAME        VARCHAR(40)    NOT NULL,
    STRUCTURER_VERSION     VARCHAR(80)    NOT NULL,
    RAW_CONFIDENCE         DOUBLE,
    CALIBRATED_CONFIDENCE  DOUBLE         NOT NULL,
    WAS_SELECTED           CHAR(1) DEFAULT 'N' NOT NULL,
    FIELD_VALUE            VARCHAR(512),
    LATENCY_MS             INT,
    COUNTRY_HINT           CHAR(2),
    CREATED_AT             TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- 008: Validation feedback
CREATE TABLE IF NOT EXISTS VALIDATION_FEEDBACK (
    FEEDBACK_ID         BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESULT_ID           BIGINT         NOT NULL,
    FIELD_NAME          VARCHAR(20)    NOT NULL,
    ORIGINAL_VALUE      VARCHAR(512),
    CORRECTED_VALUE     VARCHAR(512)   NOT NULL,
    CORRECTED_BY        VARCHAR(64)    NOT NULL,
    CORRECTED_AT        TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CORRECTION_REASON   VARCHAR(64),
    COUNTRY_HINT        CHAR(2),
    VERSION             INT DEFAULT 0 NOT NULL
);

-- 008: Accuracy samples
CREATE TABLE IF NOT EXISTS ACCURACY_SAMPLES (
    SAMPLE_ID           BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESULT_ID           BIGINT         NOT NULL,
    COUNTRY_HINT        CHAR(2)        NOT NULL,
    CONFIDENCE_BUCKET   VARCHAR(8)     NOT NULL,
    SAMPLED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    STATUS              VARCHAR(16) DEFAULT 'PENDING' NOT NULL,
    REVIEWER            VARCHAR(64),
    REVIEWED_AT         TIMESTAMP,
    PER_FIELD_VERDICT   CLOB,
    NOTES               VARCHAR(2000),
    VERSION             INT DEFAULT 0 NOT NULL
);

-- 010: Compliance routing
CREATE TABLE IF NOT EXISTS COMPLIANCE_ROUTING (
    ROUTING_ID                  BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    RESULT_ID                   BIGINT         NOT NULL,
    COUNTRY_HINT                CHAR(2),
    DECISION                    VARCHAR(20)    NOT NULL,
    PRIMARY_REASON              VARCHAR(40),
    ALL_REASONS_JSON            CLOB,
    URGENCY                     VARCHAR(16),
    ROUTED_AT                   TIMESTAMP,
    ROUTED_TO                   VARCHAR(64),
    COMPLIANCE_REQUEST_ID       VARCHAR(64),
    COMPLIANCE_VERDICT          VARCHAR(20),
    COMPLIANCE_VERDICT_DETAIL   CLOB,
    COMPLIANCE_RESPONDED_AT     TIMESTAMP,
    STATUS                      VARCHAR(16) DEFAULT 'PENDING' NOT NULL,
    CREATED_AT                  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    VERSION                     INT DEFAULT 0 NOT NULL
);

-- Legacy ADDRESS table (read-only source for backfill)
CREATE TABLE IF NOT EXISTS ADDRESS (
    PARTY_ID        VARCHAR(64),
    ADDRESS_LINE_1  VARCHAR(512),
    ADDRESS_LINE_2  VARCHAR(512),
    ADDRESS_LINE_3  VARCHAR(512),
    ADDRESS_LINE_4  VARCHAR(512),
    COUNTRY_CODE    CHAR(2),
    POSTAL_CODE     VARCHAR(20),
    LAST_UPDATED    TIMESTAMP,
    SOURCE_SYSTEM   VARCHAR(32)
);
